<?php

/**
 * @file
 * Module file.
 */

use Drupal\server_general\ArabicNumberConverter;

/**
 * Implements hook_theme_suggestions_alter().
 *
 * Adds fine-grained overrides for form templates.
 *
 * For instance for a form with an ID "server_general_foo_form", you can use
 * form--server-general-foo-form.html.twig
 *
 * That can be based on form.html.twig.
 */
function server_general_theme_suggestions_alter(array &$suggestions, array $variables) {
  if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
    $original_theme_hook = $variables['theme_hook_original'];
    $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);
  }
  return $suggestions;
}

/**
 * Implements hook_intl_date_formatted_date_alter().
 */
function server_general_intl_date_formatted_date_alter(string &$formatted_date, array $context) {
  switch ($context['langcode']) {
    case 'ar':
      // Change Arabic numbers to Latin numbers.
      $formatted_date = ArabicNumberConverter::arToEn($formatted_date);
      break;

    case 'ru':
      // Uppercase the text parts of the date in Russian.
      $formatted_date = mb_convert_case($formatted_date, MB_CASE_TITLE, 'UTF-8');
      break;
  }
}
