<?php

/**
 * @file
 * Functionality for the Style guide module.
 */

/**
 * Implements hook_theme().
 */
function server_style_guide_theme() {
  $info = [];

  $info['server_style_guide_header'] = [
    'variables' => [
      'title' => NULL,
      // The unique HTML id (e.g. `#foo`). We don't use the reserved `#id`.
      'unique_id' => NULL,
      // Optional; a link to the design.
      'link' => NULL,
    ],
  ];

  // Wrap all style guide elements.
  $info['server_style_guide_wrapper'] = [
    'variables' => [
      'elements' => [],
    ],
  ];

  // A single element wrapper, with no container.
  $info['server_style_guide_no_container'] = [
    'variables' => [
      'title' => NULL,
      'element' => [],
    ],
  ];

  // A single element wrapper, with a wide container.
  $info['server_style_guide_wide_container'] = [
    'variables' => [
      'title' => NULL,
      'element' => [],
    ],
  ];



  return $info;
}
