#!/bin/bash

## Description: Run PhpStan inside the container
## Usage: phpstan
## Example: "ddev phpstan"

if [ $# -eq 0 ]; then
  # No arguments provided, run default analyse command
  PHP_MEMORY_LIMIT=2G ./vendor/bin/phpstan --no-progress analyse -c phpstan.neon
else
  # Arguments provided, pass them through with configuration
  PHP_MEMORY_LIMIT=2G ./vendor/bin/phpstan "$@" -c phpstan.neon
fi
