#!/bin/bash

## Description: Run PHPunit tests inside the web container.
## Usage: phpunit [arguments]
## Example: "ddev phpunit" or "ddev phpunit web/modules/custom/server_general".

if [ $# -eq 0 ]; then
  # If no arguments are provided, run non-Rollbar tests
  ./vendor/bin/phpunit -c phpunit.xml.dist --exclude-group=Rollbar
else
  # If arguments are provided, pass them to PHPUnit
  ./vendor/bin/phpunit -c phpunit.xml.dist "$@"
fi
