#!/bin/bash

## #ddev-generated
## Description: Run robo commands inside the web container.
## Usage: robo
## Example: "ddev robo compile:theme" or "ddev robo compile:theme-debug".

cd .. && ./vendor/bin/robo $@
