#!/bin/bash

# ---------------------------------------------------------------------------- #
#
# Run the coder review.
#
# ---------------------------------------------------------------------------- #

export PATH="$PATH:$HOME/.composer/vendor/bin"
phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer

HAS_ERRORS=0
LOCAL_MODE=1
FIX_MODE=1
STD="$1"

##
# Function to run the actual code review
#
# This function takes 2 params:
# @param string $1
#   The file path to the directory or file to check.
# @param string $2
#   The ignore pattern(s).
##
code_review () {

  echo "${LWHITE}$1${RESTORE}"

  phpcbf --standard=Drupal -p --colors --ignore=profiles/contrib/* --extensions=php,module,inc,install,test,profile,theme,js,css "${1#web/}"
  phpcs --standard=Drupal -p --colors --ignore=profiles/contrib/* --extensions=php,module,inc,install,test,profile,theme,js,css "${1#web/}"
  if [ $? -ne 0 ]; then
    HAS_ERRORS=1
  fi

  phpcbf --standard=DrupalPractice -p --colors --ignore=profiles/contrib/* --extensions=php,module,inc,install,test,profile,theme,js,css "${1#web/}"
  phpcs --standard=DrupalPractice -p --colors --ignore=profiles/contrib/* --extensions=php,module,inc,install,test,profile,theme,js,css "${1#web/}"
  if [ $? -ne 0 ]; then
    HAS_ERRORS=1
  fi
}

if [[ -d "modules/custom" ]];
then
  echo
  echo "${LBLUE}> Correcting Modules to follow the '${REVIEW_STANDARD}' standard. ${RESTORE}"

  for dir in modules/custom/*/ ; do
    code_review "$dir"
  done
fi

echo "${LBLUE}> Correcting Profile to follow the '${REVIEW_STANDARD}' standard. ${RESTORE}"

for dir in profiles/*/ ; do
  code_review "$dir"
done

exit $HAS_ERRORS
