#!/bin/bash

## Description: Run theme compile, watch for changes.
## Usage: theme:watch
## Aliases: theme-watch
## Example: "ddev theme:watch"

cd ./web/themes/custom/server_theme && npx tailwindcss -i ./src/css/style.css -o ./dist/css/style.css --watch
