#!/bin/bash

## Description: Compile the theme.
## Usage: theme:compile
## Aliases: theme-compile
## Example: "ddev theme:compile"

cd ./web/themes/custom/server_theme && npm install && npm run build
