#!/bin/bash

## Description: Run theme compile, watch for changes.
## Usage: theme:watch
## Example: "ddev theme:watch"

cd ./web/themes/custom/server_theme && npx @tailwindcss/cli -i ./src/pcss/style.css -o ./dist/css/style.css --watch
