#!/bin/bash

## Description: Run Tailwind CSS compile, watch for changes.
## Usage: tw
## Example: "ddev tw"

cd ./web/themes/custom/server_theme && npx tailwindcss -i ./src/scss/style.pcss -o ./dist/css/style.css --watch
