#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev get ddev/ddev-selenium-standalone-chrome
#
# This file comes from https://github.com/ddev/ddev-selenium-standalone-chrome
#
services:
  selenium-chrome:
    image: selenium/standalone-chromium:138.0
    container_name: ddev-${DDEV_SITENAME}-selenium-chrome
    expose:
      #      The internal noVNC port, which operates over HTTP so it can be exposed
      #      through the router.
      - 7900
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=7900:7900
      - HTTP_EXPOSE=7910:7900
      - VNC_NO_PASSWORD=1
    # To enable VNC access for traditional VNC clients like macOS "Screen Sharing",
    # uncomment the following two lines.
    #ports:
    #  - "5900:5900"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      # To enable file uploads in E2E tests.
      - ${DDEV_APPROOT}:/var/www/html:r
      - ".:/mnt/ddev_config"

  web:
    links:
      - selenium-chrome
